### ISSUE TITLE
[Feature Request] Implement compatibility with controller configurations from desktop Dolphin

### ISSUE THREAD

**Issue by HStephens05** [OatmealDome/dolphin-ios#38]
With the current issues regarding controller mapping, it would be beneficial if we could import configs from desktop versions of Dolphin and have them work with DolphiniOS as well.

**Comment by OatmealDome** [comment]
Unfortunately, this isn't really feasible due to how Dolphin's controller configuration system works.

Dolphin on PC / Mac has a large amount of different input backends, and button + device names will differ between them. There is no guarantee that names in those backends will match the ones that the sole input backend on DolphiniOS (MFi) uses.
