### ISSUE TITLE
Dolphinios crashes whenever I exit emulation

### ISSUE THREAD

**Issue by gollygoose** [OatmealDome/dolphin-ios#94]
The emulator crashes whenever I choose to exit a game, no matter which game it is (the games work fine though.) Kind of annoying as I have to enable jit all over again. Is this normal or is there a way to fix this?

IPad Pro M2. iPadOS 16.1
Version 3.2.1b1

**Comment by OatmealDome** [comment]
Thank you for your report. We are no longer accepting issues for the 3.x.x version series, as we have restarted development from scratch using a new codebase and are no longer updating 3.x.x (because of odd issues like these). If you are willing to try a 4.0.0 beta build and you find that it still occurs, feel free to open another issue.
